finalWebsite/appartement/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('creer_appartement/', views.creer_appartement, name='creer_appartement'),
    path('creer_maison/', views.creer_maison, name='creer_maison'),
    path('prediction_result/<str:prediction_type>/<int:prediction_id>/', views.prediction_result, name='prediction_result'),
    path('get_estimates/', views.get_estimates, name='get_estimates'),

]

finalWebsite/finalWebsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('appartement.urls')),  # Inclure les URLs de l'application 'appartement'
]

finalWebsite/appartement/models.py
from django.db import models
from django.utils import timezone
import pandas as pd


REGIONS_CHOICES = [
    ('', 'Sélectionnez votre région'),
    ('Auvergne-Rhône-Alpes', 'Auvergne-Rhône-Alpes'),
    ('Bourgogne-Franche-Comté', 'Bourgogne-Franche-Comté'),
    ('Bretagne', 'Bretagne'),
    ('Centre-Val de Loire', 'Centre-Val de Loire'),
    ('Corse', 'Corse'),
    ('Grand Est', 'Grand Est'),
    ('Hauts-de-France', 'Hauts-de-France'),
    ('Île-de-France', 'Île-de-France'),
    ('Normandie', 'Normandie'),
    ('Nouvelle-Aquitaine', 'Nouvelle-Aquitaine'),
    ('Occitanie', 'Occitanie'),
    ('Pays de la Loire', 'Pays de la Loire'),
    ('Provence-Alpes-Côte d\'Azur', 'Provence-Alpes-Côte d\'Azur')
]

TYPES_VOIE_CHOICES = [
    ('', '---'),
    ('ALL', 'Allée'),
    ('AV', 'Avenue'),
    ('BD', 'Boulevard'),
    ('CHE', 'Chemin'),
    ('RUE', 'Rue'),
    ('RTE', 'Route'),
    ('IMP', 'Impasse'),
    ('QUAI', 'Quai'),
    ('PL', 'Place'),
    ('PARC', 'Parc'),
    ('CRS', 'Cours'),
    ('RES', 'Résidence'),
    ('FG', 'Faubourg'),
    ('VOIE', 'Voie'),
    ('PTR', 'Porte'),
    ('PAS', 'Passage'),
    ('MAIL', 'Mail'),
    ('SEN', 'Sentier'),
    ('PTE', 'Petite Rue'),
    ('TRT', 'Traversée'),
    ('ZAC', 'Zone d\'Activité Commerciale'),
    ('ZI', 'Zone Industrielle')
]

SUFFIXE_CHOICES = [
    ('', '---'),
    ('T', 'Ter'),
    ('A', 'A'),
    ('B', 'Bis'),
    ('D', 'D'),
    ('G', 'G'),
    ('C', 'C'),
    ('F', 'F'),
    ('Q', 'Quater'),
]
    
class PredictionAppart(models.Model):
    adresse_numero = models.CharField(max_length=10, default='')
    adresse_suffixe = models.CharField(max_length=2, choices=SUFFIXE_CHOICES, blank=True, null=True, default='')
    adresse_code_voie = models.CharField(max_length=100, choices=TYPES_VOIE_CHOICES, default='')
    adresse_nom_voie = models.CharField(max_length=100, default='')
    code_postal = models.CharField(max_length=10)
    ville = models.CharField(max_length=100, blank=True)
    region = models.CharField(max_length=100, choices=REGIONS_CHOICES, default='')
    departement = models.CharField(max_length=100)
    superficie = models.FloatField()
    nombre_de_pieces = models.IntegerField()
    etage = models.IntegerField()
    ascenseur = models.BooleanField(default=False)
    prix_estime = models.FloatField()
    date_predicted = models.DateTimeField(default=timezone.now)


class PredictionMaison(models.Model):
    adresse_numero = models.CharField(max_length=10, default='')
    adresse_suffixe = models.CharField(max_length=2, choices=SUFFIXE_CHOICES, blank=True, null=True, default='')
    adresse_code_voie = models.CharField(max_length=100, choices=TYPES_VOIE_CHOICES, default='')
    adresse_nom_voie = models.CharField(max_length=100, default='')
    code_postal = models.CharField(max_length=10)
    ville = models.CharField(max_length=100, blank=True)
    region = models.CharField(max_length=100, choices=REGIONS_CHOICES, default='')
    departement = models.CharField(max_length=100)
    superficie = models.FloatField()
    nombre_de_pieces = models.IntegerField()
    superficie_terrain = models.FloatField()
    prix_estime = models.FloatField()
    date_predicted = models.DateTimeField(default=timezone.now)


class Transformer:
    data: pd.DataFrame
    X: pd.DataFrame
    y: pd.Series

    def fit(self, data):
        self.data = pd.DataFrame()
        column = 'date-mutation'

        df = pd.to_datetime(data[column], format='%Y-%m-%d')
        self.data['year'] = df.dt.year
        self.data['month'] = df.dt.month
        self.data['day'] = df.dt.day

        column = 'no-voie'
        self.data[column] = data[column].astype('Int64')

        column = 'b/t/q'
        self.data[column] = data[column].astype('category')

        column = 'type-de-voie'
        self.data[column] = data[column].astype('category')

        column = 'voie'
        self.data[column] = data[column].astype('category')
        # TODO: in the next step we will
        # convert the address to a coordinate
        # two columns: latitude and longitude
        column = 'code-postal'
        self.data[column] = data[column].astype('Int64')

        column = 'type-local'
        self.data[column] = data[column].astype('category')

        column = 'surface-terrain'
        self.data[column] = data[column]

        column = 'surface-reelle-bati'
        self.data[column] = data[column]

        column = 'nombre-pieces-principales'
        self.data[column] = data[column].astype('Int64')

        # Let it here.
        self.X = self.data.copy()
        for column in self.X.columns:
            if self.X[column].dtype.name == 'category':
                self.X[column] = self.X[column].cat.codes
        self.y = data['valeur-fonciere']

        return self

    def transform(self, data):
        X = pd.DataFrame()

        column = 'date-mutation'
        df = pd.to_datetime(data[column], format='%Y-%m-%d')
        X['year'] = df.dt.year
        X['month'] = df.dt.month
        X['day'] = df.dt.day

        column = 'no-voie'
        X[column] = data[column].astype('Int64')

        column = 'b/t/q'
        X[column] = data[column].apply(
            lambda x: self.data[column].cat.categories.get_loc(x) if x in self.data[column].cat.categories else -1
        )

        column = 'type-de-voie'
        X[column] = data[column].apply(
            lambda x: self.data[column].cat.categories.get_loc(x) if x in self.data[column].cat.categories else -1
        )

        column = 'voie'
        X[column] = data[column].apply(
            lambda x: self.data[column].cat.categories.get_loc(x) if x in self.data[column].cat.categories else -1
        )

        column = 'code-postal'
        X[column] = data[column].astype('Int64')

        column = 'type-local'
        X[column] = data[column].apply(
            lambda x: self.data[column].cat.categories.get_loc(x) if x in self.data[column].cat.categories else -1
        )

        column = 'surface-terrain'
        X[column] = data[column]

        column = 'surface-reelle-bati'
        X[column] = data[column]

        column = 'nombre-pieces-principales'
        X[column] = data[column].astype('Int64')

        return X

    def save(self, path):
        self.data.to_csv(path, index=False)


def load_transformer(path: str) -> Transformer:
    transformer = Transformer()
    data = pd.read_csv(path)
    transformer.data = data

    columns = [
        'b/t/q',
        'type-de-voie',
        'voie',
        'type-local'
    ]
    for column in columns:
        transformer.data[column] = transformer.data[column].astype('category')

    columns = [
        'no-voie',
        'code-postal',
        'nombre-pieces-principales'
    ]
    for column in columns:
        transformer.data[column] = transformer.data[column].astype('Int64')

    return transformer

finalWebsite/appartement/forms.py
from django import forms
from .models import PredictionAppart, PredictionMaison, REGIONS_CHOICES, TYPES_VOIE_CHOICES, SUFFIXE_CHOICES
from django.utils import timezone


class AppartementForm(forms.ModelForm):
    nombre_de_pieces = forms.IntegerField(initial=0)
    etage = forms.IntegerField(initial=0)
    region = forms.ChoiceField(choices=REGIONS_CHOICES, label="Région")
    departement = forms.CharField(label="Département", max_length=100)
    adresse_suffixe = forms.ChoiceField(choices=SUFFIXE_CHOICES, label='Suffixe d\'adresse', required=False, initial='')
    adresse_code_voie = forms.ChoiceField(choices=TYPES_VOIE_CHOICES, label='Type de voie')

    class Meta:
        model = PredictionAppart
        fields = ['adresse_numero', 'adresse_suffixe', 'adresse_code_voie', 'adresse_nom_voie', 'code_postal', 'ville', 'region', 'departement', 'superficie', 'nombre_de_pieces', 'etage', 'ascenseur']
        widgets = {
            'region': forms.Select(choices=REGIONS_CHOICES),
            'adresse_suffixe': forms.Select(choices=SUFFIXE_CHOICES),
            'adresse_code_voie': forms.Select(choices=TYPES_VOIE_CHOICES),
        }

class MaisonForm(forms.ModelForm):
    nombre_de_pieces = forms.IntegerField(initial=0)
    region = forms.ChoiceField(choices=REGIONS_CHOICES, label="Région", initial='')
    departement = forms.CharField(label="Département", max_length=100)
    adresse_suffixe = forms.ChoiceField(choices=SUFFIXE_CHOICES, label='Suffixe d\'adresse', required=False, initial='')
    adresse_code_voie = forms.ChoiceField(choices=TYPES_VOIE_CHOICES, label='Type de voie', initial='')

    class Meta:
        model = PredictionMaison
        fields = ['adresse_numero', 'adresse_suffixe', 'adresse_code_voie', 'adresse_nom_voie', 'code_postal', 'ville', 'region', 'departement', 'superficie', 'nombre_de_pieces', 'superficie_terrain']
        widgets = {
            'region': forms.Select(choices=REGIONS_CHOICES),
            'adresse_suffixe': forms.Select(choices=SUFFIXE_CHOICES),
            'adresse_code_voie': forms.Select(choices=TYPES_VOIE_CHOICES),
        }

finalWebsite/appartement/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .forms import AppartementForm, MaisonForm
from . import prediction
from .models import PredictionAppart, PredictionMaison
import json
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
avg_file_path = os.path.join(BASE_DIR, 'average_prices_by_departement.json')

def creer_appartement(request):
    if request.method == 'POST':
        form = AppartementForm(request.POST)
        if form.is_valid():
            adresse_numero = form.cleaned_data['adresse_numero']
            adresse_suffixe = form.cleaned_data['adresse_suffixe']
            adresse_code_voie = form.cleaned_data['adresse_code_voie']
            adresse_nom_voie = form.cleaned_data['adresse_nom_voie']
            region = form.cleaned_data['region']
            departement = form.cleaned_data['departement']
            ville = form.cleaned_data['ville']
            code_postal = form.cleaned_data['code_postal']
            superficie = form.cleaned_data['superficie']
            nombre_de_pieces = form.cleaned_data['nombre_de_pieces']
            etage = form.cleaned_data['etage']
            ascenseur = form.cleaned_data['ascenseur']

            prix_estime = prediction.predict_price_appartement(adresse_numero, adresse_suffixe, adresse_code_voie, adresse_nom_voie, region, code_postal, superficie, nombre_de_pieces, etage, ascenseur)
            prix_estime = int(prix_estime)
            prix_m2 = prix_estime / superficie

            prediction_appart = PredictionAppart.objects.create(
                adresse_numero=adresse_numero,
                adresse_suffixe=adresse_suffixe,
                adresse_code_voie=adresse_code_voie,
                adresse_nom_voie=adresse_nom_voie,
                region=region,
                departement=departement,
                ville=ville,
                code_postal=code_postal,
                superficie=superficie,
                nombre_de_pieces=nombre_de_pieces,
                etage=etage,
                ascenseur=ascenseur,
                prix_estime=prix_estime
            )
            print(adresse_code_voie)
            return redirect('prediction_result', prediction_type='appartement', prediction_id=prediction_appart.id)
        else:
            # Debug message
            print("Formulaire non valide")
            print(form.errors)
    else:
        form = AppartementForm()

    return render(request, 'creer_appartement.html', {'form': form})

def creer_maison(request):
    if request.method == 'POST':
        form = MaisonForm(request.POST)
        if form.is_valid():
            adresse_numero = form.cleaned_data['adresse_numero']
            adresse_suffixe = form.cleaned_data['adresse_suffixe']
            adresse_code_voie = form.cleaned_data['adresse_code_voie']
            adresse_nom_voie = form.cleaned_data['adresse_nom_voie']
            region = form.cleaned_data['region']
            departement = form.cleaned_data['departement']
            ville = form.cleaned_data['ville']
            code_postal = form.cleaned_data['code_postal']
            superficie = form.cleaned_data['superficie']
            superficie_terrain = form.cleaned_data['superficie_terrain']
            nombre_de_pieces = form.cleaned_data['nombre_de_pieces']

            prix_estime = prediction.predict_price_maison(adresse_numero, adresse_suffixe, adresse_code_voie, adresse_nom_voie, region, code_postal, superficie, superficie_terrain, nombre_de_pieces)
            prix_estime = int(prix_estime)
            prix_m2 = prix_estime / superficie

            prediction_maison  = PredictionMaison.objects.create(
                adresse_numero=adresse_numero,
                adresse_suffixe=adresse_suffixe,
                adresse_code_voie=adresse_code_voie,
                adresse_nom_voie=adresse_nom_voie,
                code_postal=code_postal,
                region=region,
                departement=departement,
                ville=ville,
                superficie=superficie,
                superficie_terrain=superficie_terrain,
                nombre_de_pieces=nombre_de_pieces,
                prix_estime=prix_estime
            )

            return redirect('prediction_result', prediction_type='maison', prediction_id=prediction_maison.id)
        else:
            # Debug message
            print("Formulaire non valide")
            print(form.errors)
    else:
        form = MaisonForm()

    return render(request, 'creer_maison.html', {'form': form})


def prediction_result(request, prediction_type, prediction_id):
    if prediction_type == 'appartement':
        prediction = PredictionAppart.objects.get(id=prediction_id)
    elif prediction_type == 'maison':
        prediction = PredictionMaison.objects.get(id=prediction_id)
    else:
        prediction = None

    if prediction:
        prix_m2 = prediction.prix_estime / prediction.superficie
    else:
        prix_m2 = None

    return render(request, 'prediction_result.html', {'prediction': prediction, 'type': prediction_type, 'prix_m2': prix_m2})

def get_estimates(request):
    departement = request.GET.get('departement')
    if not departement:
        return JsonResponse({'error': 'Missing departement parameter'}, status=400)
    
    try:
        with open(avg_file_path, 'r', encoding='utf-8') as json_file:
            average_prices = json.load(json_file)

        data = average_prices.get(departement, {})
        if not data:
            return JsonResponse({'error': 'No data found for this departement'}, status=404)

        response_data = {
            'appartement': {
                'moyenne': data.get('appartement', {}).get('average_price', 'N/A'),
                'moyenne_sqm': data.get('appartement', {}).get('average_price_per_sqm', 'N/A')
            },
            'maison': {
                'moyenne': data.get('maison', {}).get('average_price', 'N/A'),
                'moyenne_sqm': data.get('maison', {}).get('average_price_per_sqm', 'N/A')
            }
        }
        return JsonResponse(response_data)
    
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)

def home(request):
    predictions_appart = PredictionAppart.objects.all().order_by('-date_predicted')[:10]
    predictions_maison = PredictionMaison.objects.all().order_by('-date_predicted')[:10]
    with open(avg_file_path, 'r', encoding='utf-8') as json_file:
        average_prices = json.load(json_file)
    return render(request, 'home.html', {
        'predictions_appart': predictions_appart,
        'predictions_maison': predictions_maison,
        'average_prices': json.dumps(average_prices)
    })

finalWebsite/appartement/templates/creer_appartement.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prédire le prix d'un appartement</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
    <style>

body {
            padding-top: 60px;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        header {
            top: 0;
            left: 0;
            width: 100%;
            z-index: 1000;
            background-color: #333;
            padding: 10px 20px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

.header .back-button {
            display: block;
            margin: 20px auto;
            padding: 10px 20px;
            background-color: #f0f0f0;
            border: 1px solid #ccc;
            border-radius: 5px;
            text-align: center;
            text-decoration: none;
            color: #333;
        }
.container {
    max-width: 800px;
    margin: 100px auto;
    padding: 50px;
    background-color: rgba(255, 255, 255, 0.9);
    border-radius: 20px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}
h1 {
    text-align: center;
    margin-bottom: 20px;
    font-size: 24px;
}
.mandatory-note {
    margin-top: 10px;
    font-size: 14px;
    color: #555;
    text-align: center;
}
.ui.action.input input[type="number"] {
    border-radius: 0 5px 5px 0 !important;
}
.ui.buttons .ui.button {
    padding: 0 10px;
}
.ui.buttons .ui.button:first-child {
    border-radius: 5px 0 0 5px !important;
}
.ui.buttons .ui.button:last-child {
    border-radius: 0 5px 5px 0 !important;
}
.ui.right.labeled.input .ui.label {
    border-radius: 0 5px 5px 0 !important;
}

    </style>
</head>
<body>
    <div class="header">
        <a href="/" class="ui button back-button">Accueil</a>
    </div>
    <div class="container">
        <h1>Estimez le prix de vente de votre appartement</h1>
        <form class="ui form" method="post" action="{% url 'creer_appartement' %}">
            {% csrf_token %}
            <div class="two fields">
                <div class="field">
                    <label for="id_adresse_numero">N° Voie*</label>
                    <div class="ui input">
                        {{ form.adresse_numero }}
                    </div>
                </div>
                <div class="field">
                    <label for="id_adresse_suffixe">B/T/Q</label>
                    <div class="ui input">
                        {{ form.adresse_suffixe }}
                    </div>
                </div>
            </div>

            <div class="field">
                <label for="id_adresse_code_voie">Type de Voie*</label>
                <div class="ui input">
                    {{ form.adresse_code_voie }}
                </div>
            </div>

            <div class="field">
                <label for="id_adresse_nom_voie">Nom de la Voie*</label>
                <div class="ui input">
                    {{ form.adresse_nom_voie }}
                </div>
            </div>

            <div class="field">
                <label for="id_region">Région*</label>
                <div class="ui input">
                    {{ form.region }}
                </div>
            </div>

            <div class="field">
                <label for="id_departement">Département*</label>
                <select id="id_departement" name="departement">
                    <option value="">Sélectionnez votre département</option>
                    <!-- Les départements seront ajoutés ici dynamiquement -->
                </select>
            </div>

            <div class="field">
                <label for="id_ville">Ville*</label>
                <div class="ui input">
                    {{ form.ville }}
                </div>
            </div>

            <div class="field">
                <label for="id_code_postal">Code postal*</label>
                <div class="ui input">
                    {{ form.code_postal }}
                </div>
            </div>

            <div class="field">
                <label for="id_superficie">Surface (m²)*</label>
                <div class="ui right labeled input">
                    {{ form.superficie }}
                    <div class="ui label">m²</div>
                </div>
            </div>

            <div class="two fields">
                <div class="field">
                    <label for="id_nombre_de_pieces">Nombre de pièces*</label>
                    <div class="ui action input">
                        {{ form.nombre_de_pieces }}
                        <div class="ui buttons">
                            <button type="button" class="ui button" onclick="document.getElementById('id_nombre_de_pieces').stepDown()">-</button>
                            <button type="button" class="ui button" onclick="document.getElementById('id_nombre_de_pieces').stepUp()">+</button>
                        </div>
                    </div>
                </div>
                <div class="field">
                    <label for="id_etage">Étage*</label>
                    <div class="ui action input">
                        {{ form.etage }}
                        <div class="ui buttons">
                            <button type="button" class="ui button" onclick="document.getElementById('id_etage').stepDown()">-</button>
                            <button type="button" class="ui button" onclick="document.getElementById('id_etage').stepUp()">+</button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="fields">
                <div class="field">
                    <div class="ui checkbox">
                        {{ form.ascenseur }}
                        <label for="ascenseur">Ascenseur</label>
                    </div>
                </div>
            </div>
            <button type="submit" class="ui green button">Prédire le prix</button>
        </form>
        <p class="mandatory-note">* Correspond à un champ obligatoire</p>
    </div>

    <script>
        const departements = {
            "Auvergne-Rhône-Alpes": ["Ain (01)", "Allier (03)", "Ardèche (07)", "Cantal (15)", "Drôme (26)", "Isère (38)", "Loire (42)", "Haute-Loire (43)", "Puy-de-Dôme (63)", "Rhône (69)", "Savoie (73)", "Haute-Savoie (74)"],
            "Bourgogne-Franche-Comté": ["Côte-d'Or (21)", "Doubs (25)", "Jura (39)", "Nièvre (58)", "Haute-Saône (70)", "Saône-et-Loire (71)", "Yonne (89)", "Territoire de Belfort (90)"],
            "Bretagne": ["Côtes-d'Armor (22)", "Finistère (29)", "Ille-et-Vilaine (35)", "Morbihan (56)"],
            "Centre-Val de Loire": ["Cher (18)", "Eure-et-Loir (28)", "Indre (36)", "Indre-et-Loire (37)", "Loir-et-Cher (41)", "Loiret (45)"],
            "Corse": ["Corse-du-Sud (2A)", "Haute-Corse (2B)"],
            "Grand Est": ["Ardennes (08)", "Aube (10)", "Marne (51)", "Haute-Marne (52)", "Meurthe-et-Moselle (54)", "Meuse (55)", "Moselle (57)", "Bas-Rhin (67)", "Haut-Rhin (68)", "Vosges (88)"],
            "Hauts-de-France": ["Aisne (02)", "Nord (59)", "Oise (60)", "Pas-de-Calais (62)", "Somme (80)"],
            "Île-de-France": ["Paris (75)", "Seine-et-Marne (77)", "Yvelines (78)", "Essonne (91)", "Hauts-de-Seine (92)", "Seine-Saint-Denis (93)", "Val-de-Marne (94)", "Val-d'Oise (95)"],
            "Normandie": ["Calvados (14)", "Eure (27)", "Manche (50)", "Orne (61)", "Seine-Maritime (76)"],
            "Nouvelle-Aquitaine": ["Charente (16)", "Charente-Maritime (17)", "Corrèze (19)", "Creuse (23)", "Dordogne (24)", "Gironde (33)", "Landes (40)", "Lot (46)", "Lot-et-Garonne (47)", "Pyrénées-Atlantiques (64)", "Deux-Sèvres (79)", "Vienne (86)", "Haute-Vienne (87)"],
            "Occitanie": ["Ariège (09)", "Aude (11)", "Aveyron (12)", "Gard (30)", "Haute-Garonne (31)", "Gers (32)", "Hérault (34)", "Lot (46)", "Lozère (48)", "Hautes-Pyrénées (65)", "Pyrénées-Orientales (66)", "Tarn (81)", "Tarn-et-Garonne (82)"],
            "Pays de la Loire": ["Loire-Atlantique (44)", "Maine-et-Loire (49)", "Mayenne (53)", "Sarthe (72)", "Vendée (85)"],
            "Provence-Alpes-Côte d'Azur": ["Alpes-de-Haute-Provence (04)", "Hautes-Alpes (05)", "Alpes-Maritimes (06)", "Bouches-du-Rhône (13)", "Var (83)", "Vaucluse (84)"]
        };

        document.getElementById('id_region').addEventListener('change', function() {
            const regionSelect = this;
            const departementSelect = document.getElementById('id_departement');
            const selectedRegion = regionSelect.value;

            // Clear current options
            departementSelect.innerHTML = '<option value="">Sélectionnez votre département</option>';

            if (selectedRegion && departements[selectedRegion]) {
                departements[selectedRegion].forEach(departement => {
                    const option = document.createElement('option');
                    option.value = departement.split(' ')[1].replace('(', '').replace(')', '');
                    option.textContent = departement;
                    departementSelect.appendChild(option);
                });
            }
        });
    </script>

</body>
</html>

finalWebsite/appartement/templates/prediction_result.html
{% load static %}
{% load custom_filters %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Résultat de la Prédiction</title>
    <style>

        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .header {
            font-family: 'Arial', sans-serif;
            width: 100%;
            padding: 20px 0;
            color: white;
            display: flex;
            align-items: center;
            justify-content: space-between;
            top: 0;
            left: 0;
            right: 0;
            z-index: 1000;
            font-size: 24px;
        }
        .header .title {
            flex-grow: 1;
            text-align: center;
            margin: 0;
        }
        .container {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }
        .result-box {
            background-color: #f9f9f9;
            padding: 40px;
            border-radius: 10px;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);
            text-align: center;
            max-width: 400px;
            width: 100%;
        }
        .result-box h2 {
            margin-bottom: 20px;
        }
        .result-box .price {
            font-size: 2em;
            font-weight: bold;
            margin: 10px 0;
        }
        .result-box .price-per-m2 {
            font-size: 1.2em;
            margin-bottom: 30px;
            color: #555;
        }
        .result-box .home-button {
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }
        .result-box .home-button:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="result-box">
            <h2>Estimation pour votre {{ type|capfirst }}</h2>
            <div class="price">{{ prediction.prix_estime|intspace }} €</div>
            <div class="price-per-m2">{{ prix_m2|intspace }} €/m²</div>
            <a href="{% url 'home' %}" class="home-button">Retour à l'accueil</a>
        </div>
    </div>

    <script>
        // Fonction pour formater les nombres avec séparateurs de milliers et deux décimales
        function formatNumber(value, decimals = 2) {
            const formatter = new Intl.NumberFormat('fr-FR', {
                minimumFractionDigits: decimals,
                maximumFractionDigits: decimals
            });
            return formatter.format(value);
        }
    
        document.addEventListener("DOMContentLoaded", function() {
            // Récupérer les éléments
            const priceElement = document.getElementById("price");
            const pricePerM2Element = document.getElementById("price-per-m2");
    
            // Formater les valeurs
            const formattedPrice = formatNumber(parseFloat(priceElement.innerText.replace(' €', '')), 0);
            const formattedPricePerM2 = formatNumber(parseFloat(pricePerM2Element.innerText.replace(' €/m²', '')), 2);
    
            // Mettre à jour les éléments avec les valeurs formatées
            priceElement.innerText = `${formattedPrice} €`;
            pricePerM2Element.innerText = `${formattedPricePerM2} €/m²`;
        });
    </script>
</body>
</html>